author = Sven Schreiber
email = svetosch@gmx.net
version = 1.1
date = 2019-07-21
description = Ridge regression
tags = C13 C20
min-version = 2016c
data-requirement = no-data-ok
gui-main = ridge
label = Ridge regression
menu-attachment = MAINWIN/Model/LinearModels
public = ridge ridge_svd ridge_naive ridge_aux
help = ridge_help.txt
sample-script = ridge_sample.inp
