author = Sven Schreiber and Artur Tarassow
email = svetosch@gmx.net
version = 1.11
date = 2020-01-12
description = Ridge regression
tags = C13 C20
min-version = 2018a
data-requirement = no-data-ok
gui-main = ridge
label = Ridge regression
menu-attachment = MAINWIN/Model/LinearModels
public = ridge ridge_svd ridge_naive ridge_aux
help = ridge_help.txt
sample-script = ridge_sample.inp
